version: 2

models:
  - name: brz_orders
    schema: raw_bronze
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: total_amount
        tests:
          - not_null
      - name: status
        tests:
          - not_null
          - accepted_values:
              values: ['pending', 'completed', 'shipped', 'cancelled', 'refunded']

  - name: brz_customers
    schema: raw_bronze
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
      - name: email
        tests:
          - not_null

  - name: slv_orders
    schema: raw_silver
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: total_amount
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      - name: status
        tests:
          - accepted_values:
              values: ['pending', 'completed', 'shipped', 'cancelled', 'refunded']

  - name: slv_customers
    schema: raw_silver
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

  - name: fct_daily_revenue
    schema: raw_gold
    columns:
      - name: order_date
        tests:
          - not_null
      - name: total_revenue
        tests:
          - not_null

  - name: dim_customer_segments
    schema: raw_gold
    columns:
      - name: segment
        tests:
          - not_null
