version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: orders_cdc
        columns:
          - name: id
            tests:
              - not_null
              - unique
          - name: customer_id
          - name: total_amount
          - name: status
          - name: created_at
          - name: updated_at
          - name: __deleted

      - name: customers_cdc
        columns:
          - name: id
            tests:
              - not_null
              - unique
          - name: full_name
          - name: email
            tests:
              - not_null
          - name: country
          - name: created_at
          - name: updated_at
          - name: __deleted
