[project]
name = "datamesh-cdc"
version = "0.1.0"
description = "Data Mesh CDC Schema-on-Write Demo"

[project.optional-dependencies]
dev = [
    "dbt-core>=1.8.0",
    "dbt-postgres>=1.8.0",
    "confluent-kafka>=2.3.0",
    "requests>=2.31.0",
    "psycopg2-binary>=2.9.9",
    "confluent-kafka[avro]>=2.3.0",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"